"""Utility and context-oriented steps."""

from goa2.engine.steps._legacy import (
    AskConfirmationStep,
    CheckAdjacencyStep,
    CheckContextConditionStep,
    CheckDistanceStep,
    CheckHeroDefeatedThisRoundStep,
    CheckUnitTypeStep,
    CombineBooleanContextStep,
    ComputeDistanceStep,
    ComputeHexStep,
    CountAdjacentEnemiesStep,
    CountCardsStep,
    CountStep,
    ForEachStep,
    LogMessageStep,
    MayRepeatNTimesStep,
    MayRepeatOnceStep,
    MultiSelectStep,
    RecordHexStep,
    RecordTargetStep,
    SetActorStep,
    SetContextFlagStep,
    ValidateRepeatStep,
)

__all__ = [
    "AskConfirmationStep",
    "CheckAdjacencyStep",
    "CheckContextConditionStep",
    "CheckDistanceStep",
    "CheckHeroDefeatedThisRoundStep",
    "CheckUnitTypeStep",
    "CombineBooleanContextStep",
    "ComputeDistanceStep",
    "ComputeHexStep",
    "CountAdjacentEnemiesStep",
    "CountCardsStep",
    "CountStep",
    "ForEachStep",
    "LogMessageStep",
    "MayRepeatNTimesStep",
    "MayRepeatOnceStep",
    "MultiSelectStep",
    "RecordHexStep",
    "RecordTargetStep",
    "SetActorStep",
    "SetContextFlagStep",
    "ValidateRepeatStep",
]
