"""Compatibility exports for selection filters."""

from goa2.engine.filters_base import FilterCondition
from goa2.engine.filters_hex import (
    ObstacleFilter,
    TerrainFilter,
    RangeFilter,
    SpawnPointFilter,
    AdjacentSpawnPointFilter,
    BattleZoneFilter,
    SpawnPointTeamFilter,
    HasEmptyNeighborFilter,
    MovementPathFilter,
    FastTravelDestinationFilter,
)
from goa2.engine.filters_units import (
    TeamFilter,
    UnitTypeFilter,
    TokenTypeFilter,
    MinionTypesFilter,
    AdjacencyFilter,
    ImmunityFilter,
    UnitOnSpawnPointFilter,
    AdjacencyToContextFilter,
    ExcludeIdentityFilter,
    ForcedMovementByEnemyFilter,
    CanBePlacedByActorFilter,
    HasMarkerFilter,
)
from goa2.engine.filters_geometry import (
    LineBehindTargetFilter,
    NotInStraightLineFilter,
    InStraightLineFilter,
    StraightLinePathFilter,
    SpaceBehindEmptyFilter,
    RelativeDistanceFilter,
    ClearLineOfSightFilter,
    BetweenHexesFilter,
)
from goa2.engine.filters_cards import (
    CardsInContainerFilter,
    PlayedCardFilter,
)
from goa2.engine.filters_composite import (
    OrFilter,
    AndFilter,
    CountMatchFilter,
)

for _name in [
    "FilterCondition",
    "ObstacleFilter",
    "TerrainFilter",
    "RangeFilter",
    "SpawnPointFilter",
    "AdjacentSpawnPointFilter",
    "BattleZoneFilter",
    "SpawnPointTeamFilter",
    "HasEmptyNeighborFilter",
    "MovementPathFilter",
    "FastTravelDestinationFilter",
    "TeamFilter",
    "UnitTypeFilter",
    "TokenTypeFilter",
    "MinionTypesFilter",
    "AdjacencyFilter",
    "ImmunityFilter",
    "UnitOnSpawnPointFilter",
    "AdjacencyToContextFilter",
    "ExcludeIdentityFilter",
    "ForcedMovementByEnemyFilter",
    "CanBePlacedByActorFilter",
    "HasMarkerFilter",
    "LineBehindTargetFilter",
    "NotInStraightLineFilter",
    "InStraightLineFilter",
    "StraightLinePathFilter",
    "SpaceBehindEmptyFilter",
    "RelativeDistanceFilter",
    "ClearLineOfSightFilter",
    "BetweenHexesFilter",
    "CardsInContainerFilter",
    "PlayedCardFilter",
    "OrFilter",
    "AndFilter",
    "CountMatchFilter",
]:
    globals()[_name].__module__ = __name__

__all__ = [
    "FilterCondition",
    "ObstacleFilter",
    "TerrainFilter",
    "RangeFilter",
    "SpawnPointFilter",
    "AdjacentSpawnPointFilter",
    "BattleZoneFilter",
    "SpawnPointTeamFilter",
    "HasEmptyNeighborFilter",
    "MovementPathFilter",
    "FastTravelDestinationFilter",
    "TeamFilter",
    "UnitTypeFilter",
    "TokenTypeFilter",
    "MinionTypesFilter",
    "AdjacencyFilter",
    "ImmunityFilter",
    "UnitOnSpawnPointFilter",
    "AdjacencyToContextFilter",
    "ExcludeIdentityFilter",
    "ForcedMovementByEnemyFilter",
    "CanBePlacedByActorFilter",
    "HasMarkerFilter",
    "LineBehindTargetFilter",
    "NotInStraightLineFilter",
    "InStraightLineFilter",
    "StraightLinePathFilter",
    "SpaceBehindEmptyFilter",
    "RelativeDistanceFilter",
    "ClearLineOfSightFilter",
    "BetweenHexesFilter",
    "CardsInContainerFilter",
    "PlayedCardFilter",
    "OrFilter",
    "AndFilter",
    "CountMatchFilter",
]
